version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database_data:/var/lib/postgresql/data

  spring_boot:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile.spring
    restart: always
    ports:
      - 8080:8080
    links:
      - db

volumes:
  database_data: {}

