version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - database_data:/var/lib/postgresql/data

  spring_boot:
    depends_on:
      - db
    build: ./Dockerfile.spring
    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - db

volumes:
  database_data: {}

